// <auto-generated />
namespace HomeW_14._08._2021_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HomeWork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomeWork));
        
        string IMigrationMetadata.Id
        {
            get { return "202108281618347_HomeWork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
